import { create } from "zustand";
import type {
  User,
  Metric,
  Objective,
  FeatureAnalytics,
  ABTest,
  CustomerSegment,
  CustomerFeedback,
  RevenueData,
  UnitEconomics,
  Project,
  Task,
  RoadmapItem,
  Competitor,
  Alert,
  Report,
  TeamMember,
  DataSource,
  Integration,
} from "@/types";

interface AppState {
  currentUser: User;
  metrics: Metric[];
  objectives: Objective[];
  featureAnalytics: FeatureAnalytics[];
  abTests: ABTest[];
  customerSegments: CustomerSegment[];
  customerFeedback: CustomerFeedback[];
  revenueData: RevenueData[];
  unitEconomics: UnitEconomics[];
  projects: Project[];
  tasks: Task[];
  roadmapItems: RoadmapItem[];
  competitors: Competitor[];
  alerts: Alert[];
  reports: Report[];
  teamMembers: TeamMember[];
  dataSources: DataSource[];
  integrations: Integration[];
  sidebarOpen: boolean;
  toggleSidebar: () => void;
}

export const useStore = create<AppState>((set) => ({
  currentUser: {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@company.com",
    role: "executive",
    department: "Product",
  },

  sidebarOpen: true,
  toggleSidebar: () => set((state) => ({ sidebarOpen: !state.sidebarOpen })),

  metrics: [
    {
      id: "1",
      name: "Monthly Recurring Revenue",
      value: 2450000,
      previousValue: 2200000,
      change: 11.4,
      changeType: "increase",
      trend: "up",
      target: 2500000,
      unit: "currency",
    },
    {
      id: "2",
      name: "Active Users",
      value: 45230,
      previousValue: 43100,
      change: 4.9,
      changeType: "increase",
      trend: "up",
      target: 50000,
      unit: "number",
    },
    {
      id: "3",
      name: "Customer Churn Rate",
      value: 3.2,
      previousValue: 4.1,
      change: -22.0,
      changeType: "decrease",
      trend: "up",
      target: 2.5,
      unit: "percent",
    },
    {
      id: "4",
      name: "Net Promoter Score",
      value: 72,
      previousValue: 68,
      change: 5.9,
      changeType: "increase",
      trend: "up",
      target: 75,
      unit: "number",
    },
    {
      id: "5",
      name: "Customer Acquisition Cost",
      value: 450,
      previousValue: 520,
      change: -13.5,
      changeType: "decrease",
      trend: "up",
      target: 400,
      unit: "currency",
    },
    {
      id: "6",
      name: "Lifetime Value",
      value: 4200,
      previousValue: 3800,
      change: 10.5,
      changeType: "increase",
      trend: "up",
      target: 4500,
      unit: "currency",
    },
  ],

  objectives: [
    {
      id: "1",
      title: "Accelerate Product-Led Growth",
      description: "Drive adoption through product excellence and viral growth mechanisms",
      owner: "Sarah Johnson",
      quarter: "Q1",
      year: 2024,
      progress: 75,
      status: "on-track",
      category: "Growth",
      keyResults: [
        {
          id: "kr1",
          description: "Increase free-to-paid conversion rate",
          currentValue: 18,
          targetValue: 25,
          unit: "%",
          progress: 72,
          status: "on-track",
        },
        {
          id: "kr2",
          description: "Achieve 50K monthly active users",
          currentValue: 45230,
          targetValue: 50000,
          unit: "users",
          progress: 90,
          status: "on-track",
        },
        {
          id: "kr3",
          description: "Reduce time-to-value to under 5 minutes",
          currentValue: 6.5,
          targetValue: 5,
          unit: "minutes",
          progress: 70,
          status: "at-risk",
        },
      ],
    },
    {
      id: "2",
      title: "Enhance Platform Scalability",
      description: "Build infrastructure to support 10x growth",
      owner: "Mike Chen",
      quarter: "Q1",
      year: 2024,
      progress: 60,
      status: "on-track",
      category: "Technology",
      keyResults: [
        {
          id: "kr4",
          description: "Reduce API response time",
          currentValue: 180,
          targetValue: 100,
          unit: "ms",
          progress: 62,
          status: "on-track",
        },
        {
          id: "kr5",
          description: "Achieve 99.9% uptime",
          currentValue: 99.7,
          targetValue: 99.9,
          unit: "%",
          progress: 80,
          status: "on-track",
        },
      ],
    },
    {
      id: "3",
      title: "Expand Enterprise Market Share",
      description: "Penetrate Fortune 500 companies with enterprise features",
      owner: "Lisa Anderson",
      quarter: "Q1",
      year: 2024,
      progress: 45,
      status: "at-risk",
      category: "Revenue",
      keyResults: [
        {
          id: "kr6",
          description: "Close 15 enterprise deals",
          currentValue: 8,
          targetValue: 15,
          unit: "deals",
          progress: 53,
          status: "at-risk",
        },
        {
          id: "kr7",
          description: "Launch SSO and advanced security features",
          currentValue: 70,
          targetValue: 100,
          unit: "%",
          progress: 70,
          status: "on-track",
        },
      ],
    },
  ],

  featureAnalytics: [
    {
      id: "1",
      featureName: "Collaborative Workspaces",
      adoptionRate: 78,
      activeUsers: 35280,
      engagementScore: 8.4,
      retentionRate: 92,
      satisfactionScore: 4.6,
    },
    {
      id: "2",
      featureName: "Advanced Reporting",
      adoptionRate: 45,
      activeUsers: 20354,
      engagementScore: 7.2,
      retentionRate: 85,
      satisfactionScore: 4.3,
    },
    {
      id: "3",
      featureName: "Mobile App",
      adoptionRate: 62,
      activeUsers: 28043,
      engagementScore: 7.8,
      retentionRate: 88,
      satisfactionScore: 4.5,
    },
    {
      id: "4",
      featureName: "API Integrations",
      adoptionRate: 34,
      activeUsers: 15378,
      engagementScore: 8.9,
      retentionRate: 95,
      satisfactionScore: 4.8,
    },
  ],

  abTests: [
    {
      id: "1",
      name: "Onboarding Flow Redesign",
      status: "running",
      startDate: "2024-01-15",
      variants: [
        {
          name: "Control",
          traffic: 50,
          conversions: 450,
          conversionRate: 18.0,
        },
        {
          name: "Variant A",
          traffic: 50,
          conversions: 525,
          conversionRate: 21.0,
        },
      ],
      metric: "Signup Completion Rate",
    },
    {
      id: "2",
      name: "Pricing Page Layout",
      status: "completed",
      startDate: "2023-12-01",
      endDate: "2024-01-10",
      variants: [
        {
          name: "Control",
          traffic: 50,
          conversions: 280,
          conversionRate: 14.0,
        },
        {
          name: "Variant B",
          traffic: 50,
          conversions: 340,
          conversionRate: 17.0,
        },
      ],
      metric: "Free Trial Signups",
      winner: "Variant B",
    },
  ],

  customerSegments: [
    {
      id: "1",
      name: "Enterprise",
      size: 234,
      percentage: 5.2,
      revenue: 1470000,
      growthRate: 23.5,
      characteristics: ["Large teams", "Custom integrations", "High LTV"],
    },
    {
      id: "2",
      name: "SMB",
      size: 1567,
      percentage: 34.6,
      revenue: 735000,
      growthRate: 18.2,
      characteristics: ["Quick adoption", "Standard features", "Price sensitive"],
    },
    {
      id: "3",
      name: "Startup",
      size: 2145,
      percentage: 47.4,
      revenue: 245000,
      growthRate: 42.1,
      characteristics: ["Fast growing", "Power users", "Early adopters"],
    },
    {
      id: "4",
      name: "Individual",
      size: 580,
      percentage: 12.8,
      revenue: 87000,
      growthRate: 8.7,
      characteristics: ["Solo users", "Basic plans", "Personal use"],
    },
  ],

  customerFeedback: [
    {
      id: "1",
      customer: "TechCorp Inc.",
      feedback: "The collaborative features have transformed how our team works. Would love to see more automation options.",
      sentiment: "positive",
      category: "Feature Request",
      date: "2024-01-18",
      priority: "high",
      status: "reviewed",
    },
    {
      id: "2",
      customer: "StartupXYZ",
      feedback: "Pricing is a bit steep for our stage. Any startup discounts available?",
      sentiment: "neutral",
      category: "Pricing",
      date: "2024-01-17",
      priority: "medium",
      status: "actioned",
    },
    {
      id: "3",
      customer: "Design Studio",
      feedback: "Mobile app needs performance improvements. Sometimes lags when loading large projects.",
      sentiment: "negative",
      category: "Bug Report",
      date: "2024-01-16",
      priority: "high",
      status: "new",
    },
  ],

  revenueData: [
    { period: "Jan", revenue: 2100000, growth: 8.5, forecast: 2200000 },
    { period: "Feb", revenue: 2250000, growth: 7.1, forecast: 2300000 },
    { period: "Mar", revenue: 2450000, growth: 8.9, forecast: 2500000 },
    { period: "Apr", revenue: 0, growth: 0, forecast: 2650000 },
    { period: "May", revenue: 0, growth: 0, forecast: 2800000 },
    { period: "Jun", revenue: 0, growth: 0, forecast: 2950000 },
  ],

  unitEconomics: [
    {
      metric: "Customer Acquisition Cost (CAC)",
      value: 450,
      previousValue: 520,
      change: -13.5,
      target: 400,
    },
    {
      metric: "Lifetime Value (LTV)",
      value: 4200,
      previousValue: 3800,
      change: 10.5,
      target: 4500,
    },
    {
      metric: "LTV:CAC Ratio",
      value: 9.3,
      previousValue: 7.3,
      change: 27.4,
      target: 10.0,
    },
    {
      metric: "Payback Period (months)",
      value: 8,
      previousValue: 11,
      change: -27.3,
      target: 6,
    },
  ],

  projects: [
    {
      id: "1",
      name: "Enterprise SSO Implementation",
      description: "Implement Single Sign-On for enterprise customers",
      status: "in-progress",
      priority: "critical",
      startDate: "2024-01-01",
      endDate: "2024-03-31",
      progress: 65,
      owner: "Mike Chen",
      team: ["Mike Chen", "Lisa Wong", "Tom Brady"],
      budget: 150000,
      spent: 97500,
    },
    {
      id: "2",
      name: "Mobile App Redesign",
      description: "Complete redesign of mobile application",
      status: "in-progress",
      priority: "high",
      startDate: "2024-01-15",
      endDate: "2024-04-30",
      progress: 40,
      owner: "Jessica Lee",
      team: ["Jessica Lee", "David Park", "Amy Zhang"],
      budget: 200000,
      spent: 80000,
    },
    {
      id: "3",
      name: "Advanced Analytics Dashboard",
      description: "Build comprehensive analytics and reporting features",
      status: "planning",
      priority: "high",
      startDate: "2024-02-01",
      endDate: "2024-05-31",
      progress: 15,
      owner: "Robert Kim",
      team: ["Robert Kim", "Emily Chen"],
      budget: 120000,
      spent: 18000,
    },
  ],

  tasks: [
    {
      id: "1",
      title: "Implement OAuth 2.0 integration",
      description: "Add OAuth 2.0 support for SSO",
      status: "in-progress",
      priority: "critical",
      assignee: "Mike Chen",
      dueDate: "2024-02-15",
      project: "Enterprise SSO Implementation",
      tags: ["backend", "security"],
    },
    {
      id: "2",
      title: "Design new dashboard layout",
      description: "Create mockups for analytics dashboard",
      status: "done",
      priority: "high",
      assignee: "Jessica Lee",
      dueDate: "2024-01-20",
      project: "Advanced Analytics Dashboard",
      tags: ["design", "ui"],
    },
    {
      id: "3",
      title: "Performance testing for mobile app",
      description: "Run comprehensive performance tests",
      status: "todo",
      priority: "high",
      assignee: "David Park",
      dueDate: "2024-02-28",
      project: "Mobile App Redesign",
      tags: ["testing", "mobile"],
    },
  ],

  roadmapItems: [
    {
      id: "1",
      title: "AI-Powered Insights",
      description: "Integrate machine learning for predictive analytics",
      category: "Product",
      status: "planned",
      priority: "must-have",
      quarter: "Q2",
      year: 2024,
      owner: "Sarah Johnson",
      impact: "high",
    },
    {
      id: "2",
      title: "Enterprise Security Suite",
      description: "Advanced security features for enterprise customers",
      category: "Security",
      status: "in-progress",
      priority: "must-have",
      quarter: "Q1",
      year: 2024,
      owner: "Mike Chen",
      dependencies: ["1"],
      impact: "high",
    },
    {
      id: "3",
      title: "Marketplace for Integrations",
      description: "App marketplace for third-party integrations",
      category: "Platform",
      status: "planned",
      priority: "should-have",
      quarter: "Q3",
      year: 2024,
      owner: "Lisa Anderson",
      impact: "medium",
    },
  ],

  competitors: [
    {
      id: "1",
      name: "CompetitorA",
      marketShare: 32,
      strengths: ["Strong brand", "Large customer base", "Enterprise focus"],
      weaknesses: ["High prices", "Slow innovation", "Poor UX"],
      recentMoves: ["Launched AI features", "Acquired startup", "Expanded to APAC"],
      threat: "high",
    },
    {
      id: "2",
      name: "CompetitorB",
      marketShare: 18,
      strengths: ["Innovative features", "Great UX", "Strong developer community"],
      weaknesses: ["Limited enterprise features", "Small team", "Funding concerns"],
      recentMoves: ["Series B funding", "Mobile app launch"],
      threat: "medium",
    },
  ],

  alerts: [
    {
      id: "1",
      title: "Churn Rate Spike Detected",
      description: "Customer churn increased by 15% in the last week",
      severity: "critical",
      category: "Metrics",
      timestamp: "2024-01-20T10:30:00Z",
      read: false,
      actionRequired: true,
    },
    {
      id: "2",
      title: "OKR Progress Behind Schedule",
      description: "Q1 OKR 'Enterprise Market Share' is 20% behind target",
      severity: "warning",
      category: "OKR",
      timestamp: "2024-01-20T09:15:00Z",
      read: false,
      actionRequired: true,
    },
    {
      id: "3",
      title: "New Feature Launch Successful",
      description: "Collaborative Workspaces reached 10K users in first week",
      severity: "info",
      category: "Product",
      timestamp: "2024-01-19T14:20:00Z",
      read: true,
      actionRequired: false,
    },
  ],

  reports: [
    {
      id: "1",
      name: "Executive Summary",
      description: "Weekly summary of key metrics and business performance",
      type: "executive",
      frequency: "weekly",
      lastGenerated: "2024-01-19T08:00:00Z",
      recipients: ["sarah.johnson@company.com", "ceo@company.com"],
    },
    {
      id: "2",
      name: "Product Performance Report",
      description: "Detailed analysis of product metrics and user engagement",
      type: "product",
      frequency: "monthly",
      lastGenerated: "2024-01-01T08:00:00Z",
      recipients: ["product-team@company.com"],
    },
  ],

  teamMembers: [
    {
      id: "1",
      name: "Mike Chen",
      role: "Senior Engineer",
      performance: 92,
      tasksCompleted: 24,
      tasksInProgress: 3,
      efficiency: 95,
    },
    {
      id: "2",
      name: "Jessica Lee",
      role: "Product Designer",
      performance: 88,
      tasksCompleted: 18,
      tasksInProgress: 4,
      efficiency: 89,
    },
    {
      id: "3",
      name: "David Park",
      role: "QA Engineer",
      performance: 85,
      tasksCompleted: 31,
      tasksInProgress: 2,
      efficiency: 87,
    },
  ],

  dataSources: [
    {
      id: "1",
      name: "Production Database",
      type: "PostgreSQL",
      status: "connected",
      lastSync: "2024-01-20T11:45:00Z",
      recordsCount: 1250000,
    },
    {
      id: "2",
      name: "Google Analytics",
      type: "Analytics",
      status: "connected",
      lastSync: "2024-01-20T11:30:00Z",
      recordsCount: 850000,
    },
    {
      id: "3",
      name: "Stripe",
      type: "Payment",
      status: "connected",
      lastSync: "2024-01-20T11:50:00Z",
      recordsCount: 45000,
    },
  ],

  integrations: [
    {
      id: "1",
      name: "Slack",
      description: "Team communication and notifications",
      category: "Communication",
      status: "active",
      icon: "MessageSquare",
      connectedAt: "2023-11-15T10:00:00Z",
    },
    {
      id: "2",
      name: "Jira",
      description: "Project management and issue tracking",
      category: "Project Management",
      status: "active",
      icon: "Trello",
      connectedAt: "2023-10-20T10:00:00Z",
    },
    {
      id: "3",
      name: "Salesforce",
      description: "CRM and sales pipeline management",
      category: "CRM",
      status: "inactive",
      icon: "Users",
    },
  ],
}));
